# Generated by Django 4.0.2 on 2022-03-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(default='default_blog.jpg', upload_to='blog/'),
        ),
    ]
