# Generated by Django 4.0.2 on 2022-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(default='default_blog.jpg', upload_to='blog/images'),
        ),
    ]
