# Generated by Django 4.0.2 on 2022-02-27 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('fixture_id', models.AutoField(primary_key=True, serialize=False)),
                ('fixture_type', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('tour', models.CharField(max_length=500)),
                ('match', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recentnews',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField(default='')),
                ('headline', models.CharField(max_length=750)),
                ('intro', models.TextField(default='')),
                ('upload_time', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('news', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Bees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
