# Generated by Django 4.0.2 on 2022-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentnews',
            name='intro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recentnews',
            name='news',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recentnews',
            name='topic',
            field=models.TextField(default=''),
        ),
    ]
