# Generated by Django 4.0.2 on 2022-02-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.fixtures')),
            ],
        ),
    ]
