# Generated by Django 4.0.2 on 2022-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_fix_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix_date',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
