# Generated by Django 4.0.2 on 2022-03-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_fix_date_date_alter_fixtures_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix_date',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='date',
            field=models.DateField(),
        ),
    ]
