# Generated by Django 4.0.2 on 2022-03-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_fix_date_date_alter_fixtures_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bees',
        ),
    ]
